// Hello, Node.js! @jdomingu19
// Udemy Course by @Klerith (2023)
// src/plugins/get-uuidv4.plugin.js

// --- Class 31: Adapter Pattern ---

// Import the external uuid library
const { v4: uuidv4 } = require("uuid");

/**
 * Adapter function for UUID generation.
 *
 * @returns A unique identifier string generated by uuid v4.
 *
 * @remarks
 * Wraps the `uuid` library to provide a consistent interface
 * for generating unique IDs in the application.
 */
const getUUIDV4 = () => {
  return uuidv4();
};

// Export the adapter function
module.exports = {
  getUUIDV4,
};
